# Generated by Django 4.2.1 on 2023-08-06 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagination_size', models.PositiveIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(8)], verbose_name='размер пагинации, объектов')),
                ('banners_count', models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='количество баннеров')),
                ('hot_deals_slider', models.PositiveIntegerField(default=9, validators=[django.core.validators.MaxValueValidator(9)], verbose_name='количество горячих предложений')),
                ('top_elements_count', models.PositiveIntegerField(default=8, validators=[django.core.validators.MaxValueValidator(8)], verbose_name='количество товаров в топе')),
                ('limited_edition_count', models.PositiveIntegerField(default=16, validators=[django.core.validators.MaxValueValidator(16)], verbose_name='количество ограниченного тиража')),
                ('maximum_number_of_viewed_products', models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='максимальное количество просмотренных товаров')),
                ('free_shipping_min_order_amount', models.DecimalField(decimal_places=2, default=2000.0, max_digits=6, verbose_name='минимальная сумма заказа для бесплатной доставки, $')),
                ('standard_shipping_price', models.DecimalField(decimal_places=2, default=200.0, max_digits=6, verbose_name='стандартная цена доставки, $')),
                ('express_shipping_price', models.DecimalField(decimal_places=2, default=500.0, max_digits=6, verbose_name='стоимость экспресс-доставки, $')),
            ],
            options={
                'verbose_name': 'настройка сайта',
                'verbose_name_plural': 'настройки сайта',
            },
        ),
    ]
